DROP TABLE IF EXISTS profile_tag;
DROP TABLE IF EXISTS question_tag;
DROP TABLE IF EXISTS tag;

DROP TABLE IF EXISTS vote;
DROP TABLE IF EXISTS option_;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS profile;
